### ISSUE TITLE
Edit Game Activity needs to be fixed

### ISSUE THREAD

**Issue by NiklasSchmidts** [RonMill/Gaminglibrary#12]
<img width="324" alt="image" src="https://user-images.githubusercontent.com/115772112/210058873-1b5ab0f3-779a-43b5-b32f-2ca83f781be6.png">

Center the text from Price and Stars so that it matches with the name

**Comment by nisc1003** [comment]
Uf dem implementing_simple_item_view branch muschd des mache.
Wenn de fertich bisch dann mach grade mol a pr. 

Gruß und Kuss
