### ISSUE TITLE
Adapter does not show new Game after inserting new Game

### ISSUE THREAD

**Issue by RoMi2100** [RonMill/Gaminglibrary#5]
Only after switching the Lists the games fetching into the new gameview
1.
![image](https://user-images.githubusercontent.com/89632654/200577264-395681d5-2bec-4895-a3b8-893416af8425.png)
2.
![image](https://user-images.githubusercontent.com/89632654/200577393-1c82a5d3-60f8-4e6a-aaf8-c6f9a3f44321.png)
3.
![image](https://user-images.githubusercontent.com/89632654/200577452-aab1b957-9d1c-4af6-867d-8bd04f048948.png)

The third game is not there :-(

**Comment by BenjaminVeit** [comment]
done
